[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

remappings = [
  "kernel/=lib/kernel.git/src/",
  "kernel-test/=lib/kernel.git/test/",
  "solady/=lib/solady/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config